```{r retreiving the done variables from the cognition tasks for atri and loni}
#| echo: false
#| eval: !expr params$cognition_task_counts
#| results: asis

cognition_map <-
  tibble::tribble(
    ~atri_task_names , ~loni_variable_names , ~cognition_labels          ,
    "recall"         , "crtt_done"          , "Cued Recall"              ,
    "dsmse"          , "dsmse_done"         , "DS Mental Status Exam"    ,
    "vmi"            , "vmi_done"           , "Visual-Motor Integration" ,
    "pegboard"       , "pp_done"            , "Purdue Pegboard"          ,
    "radd"           , "cogradd_done"       , "RADD"                     ,
    "blockhaxby"     , "cogblockhaxby_done" , "Haxby Block Design"       ,
    "blockwisc"      , "cogblockwisc_done"  , "Wisconsin Block Design"   ,
    "catdog"         , "cadt_done"          , "Stroop Dog and Cat"       ,
    "verbal"         , "cogverbal_done"     , "Verbal Fluency"           ,
  )

cogATRI <- purrr::map2(
  cognition_map[["atri_task_names"]],
  cognition_map[["loni_variable_names"]],
  .f = function(x, y) {
    cog <- atriReporter::get_cognition(done, task = x)
    dplyr::rename(cog, !!y := "done")
  }
)

id_vars <- atriReporter:::get_ids(cogATRI[[1]])
cogATRI <- purrr::reduce(cogATRI, dplyr::full_join, by = id_vars)
cogATRI$ids <- cogATRI$subject_label

if (!is.null(params$lonidir)) {
  cogATRI <- params$lonidir %>%
    abcds::read_cognitive(
      person = "participants"
    ) %>%
    dplyr::select(
      subject_label:event_sequence,
      cognition_map[["loni_variable_names"]]
    ) %>%
    atriReporter:::loni_join(
      atri_data = cogATRI,
      loni_data = .,
      variables = cognition_variables
    )
}

```


```{r add flextable for cognition_task_counts to display the number of participants with multiple visits}
#| echo: false
#| eval: !expr params$cognition_task_counts
#| results: asis

atriReporter:::format_quarto(
  "Number of Participants with Completed Cognition Tasks",
  "subsection"
)

cog_tasks <- atriReporter::multiple_count_by(
  data = cogATRI,
  names = cognition_map[["loni_variable_names"]],
  labels = cognition_map[["cognition_labels"]],
  ids = "ids",
  varname = "Cognition Task"
)

cog_time <- as.numeric(colnames(cog_tasks)[2:ncol(cog_tasks)])

cog_tasks_footnote <- paste(
  glue::glue("Numbers {min(cog_time)} to {max(cog_time)}"),
  "show how many participants completed at least that many visits."
)

cog_tasks %>%
  flextable::flextable() %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::add_footer_row(
    values = cog_tasks_footnote,
    colwidths = ncol(cog_tasks)
  ) %>%
  flextable::width(j = 1, width = 1.5) %>%
  flextable::width(j = 2:(max(cog_time) + 1), width = 3.5 / max(cog_time))

atriReporter:::format_quarto(type = "newpage")

```