

```{r get enrollment by cycle}
#| echo: false
#| eval: !expr params$enrollment_by_cycle
#| results: asis

atriReporter:::format_quarto("Enrollment by Year", "subsection")

atriReporter::create_registry_table() %>%
  flextable::width(j = 1, width = 1.25) %>%
  flextable::width(j = 2:5, width = 1)

atriReporter:::format_quarto(type = "newpage")

```



```{r retreiving demographics from atri and loni}
#| echo: false
#| eval: !expr (params$demographics) | (params$enrollment_by_cycle)
#| results: asis

# params <- list(); params$lonidir <- "/Users/bhelsel/Desktop/Data/ABCDS LONI DATA"

demoVars <- c("de_race", "de_gender", "de_ethnicity")

demoATRI <-
  atriReporter::get_demographics(
    !!!demoVars
  ) %>%
  atriReporter::calculate_age_at_visit()

if (!is.null(params$lonidir)) {
  loniAGE <- abcds::read_age_at_event(params$lonidir)
  demoATRI <-
    params$lonidir %>%
    abcds::read_simplified_demographics(
      controls = FALSE
    ) %>%
    dplyr::full_join(loniAGE, by = c("subject_label", "event_sequence")) %>%
    atriReporter:::loni_join(
      atri_data = demoATRI,
      loni_data = .,
      variables = c(demoVars, "age_at_visit")
    )
}

```


```{r retreiving demographics from atri}
#| echo: false
#| eval: !expr params$demographics
#| results: asis

atriReporter:::format_quarto("Demographics", "subsection")

if ("u01_event_code" %in% names(demoATRI)) {
  u19bl1 <- (is.na(demoATRI$u01_event_code) & demoATRI$u19_event_code == "cyc1") # U19 In LONI
  u19bl2 <- (demoATRI$event_code == "cyc1" & is.na(demoATRI$u19_event_code)) # U19 not in LONI
  u01bl <- (is.na(demoATRI$u19_event_code) & demoATRI$u01_event_code == "bl") # U01
  baseDEMO <- demoATRI[u19bl1 | u19bl2 | u01bl, ]
  baseDEMO <- baseDEMO[order(baseDEMO$ids, baseDEMO$event_code), ]
  baseDEMO <- dplyr::summarise(
    baseDEMO,
    dplyr::across(de_race:age_at_visit, \(x) dplyr::first(x, na_rm = TRUE)),
    .by = ids
  )
} else {
  baseDEMO <- demoATRI %>%
    dplyr::filter(event_code == "cyc1") %>%
    dplyr::rename(ids = subject_label)
}


baseDEMO %>%
  abcds::apply_factor_labels(ids = "ids") %>%
  dplyr::mutate(de_race = "") %>%
  dplyr::select(
    age_at_visit,
    de_gender,
    de_ethnicity,
    de_race,
    White:`American Indian/Alaskan Native`
  ) %>%
  dplyr::select(dplyr::where(~ !(all(. %in% c(0, NA))))) %>%
  dplyr::mutate(dplyr::across(dplyr::where(is.factor), forcats::fct_drop)) %>%
  gtsummary::tbl_summary(
    missing = "no",
    label = list(
      age_at_visit ~ "Age (Years)",
      de_gender ~ "Gender",
      de_ethnicity ~ "Ethnicity: Hispanic/Latino?",
      de_race ~ "Race"
    ),
    statistic = list(gtsummary::all_continuous() ~ "{mean} ± {sd}"),
    digits = list(gtsummary::all_continuous() ~ 1),
  ) %>%
  gtsummary::as_tibble() %>%
  dplyr::filter(.[[1]] != "") %>%
  flextable::flextable() %>%
  flextable::set_header_labels(
    values = c("Variable", paste0("N = ", nrow(baseDEMO)))
  ) %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::bold(i = c(1:2, 5:6), j = 1) %>%
  flextable::width(j = 1, width = 4) %>%
  flextable::width(j = 2, width = 1.5)


atriReporter:::format_quarto(type = "newpage")

```


