
```{r getting blood metadata from atri and loni for completed scans}
#| echo: false
#| eval: !expr (params$blood_draw_counts) | (params$blood_draw_counts_controls)
#| results: asis

atriReporter:::format_quarto("Blood Draw Data", type = "subsection")

count_blood <- function(controls = FALSE, lonidir = NULL) {
  bloodVars <- c("bldedtadone", "bldserdone", "paxdone")
  bloodATRI <- atriReporter::get_blood(!!!bloodVars, controls = controls)
  # colnames(bloodATRI)[which(colnames(bloodATRI) == "done")] <- "paxdone"
  id_vars <- atriReporter:::get_ids(bloodATRI)
  bloodATRI$ids <- bloodATRI$subject_label

  if (!is.null(params$lonidir)) {
    bloodATRI <- params$lonidir %>%
      abcds::read_blood(controls = controls) %>%
      atriReporter:::loni_join(
        atri_data = bloodATRI,
        loni_data = .,
        variables = bloodVars
      )
  }

  blood_counts <-
    atriReporter::multiple_count_by(
      data = bloodATRI,
      names = bloodVars,
      labels = c("Plasma", "Serum", "Paxgene"),
      ids = "ids",
      varname = "Blood Draw"
    )

  person <- ifelse(controls, "Sibling Controls", "Participants")

  return(dplyr::bind_cols(Person = person, blood_counts))
}

if (params$blood_draw_counts & params$blood_draw_counts_controls) {
  blood_counts <-
    dplyr::bind_rows(
      count_blood(lonidir = params$lonidir),
      count_blood(controls = TRUE, lonidir = params$lonidir)
    )
} else if (params$blood_draw_counts & !params$blood_draw_counts_controls) {
  blood_counts <- count_blood(lonidir = params$lonidir)
} else if (!params$blood_draw_counts & params$blood_draw_counts_controls) {
  blood_counts <- count_blood(controls = TRUE, lonidir = params$lonidir)
}


blood_time <- as.numeric(colnames(blood_counts)[3:ncol(blood_counts)])

blood_counts_footnote <- paste(
  glue::glue("Numbers {min(blood_time)} to {max(blood_time)}"),
  "show how many participants completed at least that many blood draws."
)

blood_counts %>%
  flextable::as_grouped_data(groups = "Person") %>%
  flextable::as_flextable(hide_grouplabel = TRUE) %>%
  atriReporter:::ft_add_abcds_theme(grouped_column = TRUE) %>%
  flextable::add_footer_row(
    values = blood_counts_footnote,
    colwidths = (max(blood_time) + 1)
  ) %>%
  flextable::width(j = 1, width = 1) %>%
  flextable::width(
    j = 2:(max(blood_time) + 1),
    width = 4.25 / max(blood_time)
  ) %>%
  flextable::bold(i = ~ !is.na(Person))

```

\newpage

```{r getting csf metadata from atri and loni for completed scans}
#| echo: false
#| eval: !expr (params$csf_counts) | (params$csf_counts_controls)
#| results: asis

atriReporter:::format_quarto("CSF Spinal Tap", type = "subsection")

count_csf <- function(controls = FALSE, lonidir = NULL) {
  csfATRI <- atriReporter::get_csf(done, csfvolcoll, controls = controls)
  colnames(csfATRI)[which(colnames(csfATRI) == "done")] <- "csf_done"
  id_vars <- atriReporter:::get_ids(csfATRI)
  csfATRI$ids <- csfATRI$subject_label

  if (!is.null(params$lonidir)) {
    csfATRI <- params$lonidir %>%
      abcds::read_csf(controls = controls) %>%
      atriReporter:::loni_join(
        atri_data = csfATRI,
        loni_data = .,
        variables = c("csf_done", "csfvolcoll")
      )
  }

  csfATRI$csf_valid <- csfATRI$csf_done == 1 & csfATRI$csfvolcoll > 0

  csf_counts <- atriReporter::count_by(
    data = csfATRI,
    id = ids,
    column = csf_valid
  )

  person <- ifelse(controls, "Sibling Controls", "Participants")

  return(dplyr::bind_cols(Person = person, csf_counts))
}

if (params$csf_counts & params$csf_counts_controls) {
  csf_counts <-
    dplyr::bind_rows(
      count_csf(lonidir = params$lonidir),
      count_csf(controls = TRUE, lonidir = params$lonidir)
    )
} else if (params$csf_counts & !params$csf_counts_controls) {
  csf_counts <- count_csf(lonidir = params$lonidir)
} else if (!params$csf_counts & params$csf_counts_controls) {
  csf_counts <- count_csf(controls = TRUE, lonidir = params$lonidir)
}

csf_time <- as.numeric(colnames(csf_counts)[3:ncol(csf_counts)])

csf_counts_footnote <- paste(
  glue::glue("Numbers {min(csf_time)} to {max(csf_time)}"),
  "show how many participants completed at least that many CSF Spinal Taps.",
  "A valid CSF Spinal Tap requires the variable csfvolcoll (i.e., volume collected) to be greater than 0."
)

csf_counts %>%
  dplyr::rename(`CSF Spinal Tap` = variable) %>%
  dplyr::mutate(`CSF Spinal Tap` = "Count") %>%
  flextable::as_grouped_data(groups = "Person") %>%
  flextable::as_flextable(hide_grouplabel = TRUE) %>%
  atriReporter:::ft_add_abcds_theme(grouped_column = TRUE) %>%
  flextable::add_footer_row(
    values = csf_counts_footnote,
    colwidths = (max(csf_time) + 1)
  ) %>%
  flextable::width(j = 1, width = 1.25) %>%
  flextable::width(j = 2:(max(csf_time) + 1), width = 4 / max(csf_time)) %>%
  flextable::bold(i = ~ !is.na(Person))


```


```{r get omics data from loni}
#| echo: false
#| eval: !expr params$omics
#| results: asis

atriReporter:::format_quarto("Omics Data from LONI", type = "subsection")

metabolomics <- readr::read_csv(
  list.files(
    Sys.getenv("ABCDS_LONI_DATA_DIRECTORY"),
    pattern = "ABCDS_targeted_metabolomics_unadjusted",
    full.names = TRUE
  ),
  show_col_types = FALSE
)

proteomics <- readr::read_csv(
  list.files(
    Sys.getenv("ABCDS_LONI_DATA_DIRECTORY"),
    pattern = "ABCDS_Proteomics_Results_Freeze5_19Feb2026",
    full.names = TRUE
  ),
  show_col_types = FALSE
)

proteomics_tbl <- proteomics %>%
  dplyr::filter(!is.na(subject_label)) %>%
  dplyr::distinct(subject_label, event_sequence) %>%
  dplyr::group_by(event_sequence) %>%
  dplyr::count() %>%
  dplyr::mutate(
    `Omics Type` = "Proteomics",
    event_sequence = paste0("Event Sequence ", event_sequence)
  )


metabolomics_tbl <- metabolomics %>%
  dplyr::distinct(subject_label, event_sequence) %>%
  dplyr::group_by(event_sequence) %>%
  dplyr::count() %>%
  dplyr::mutate(
    `Omics Type` = "Metabolomics",
    event_sequence = paste0("Event Sequence ", event_sequence)
  )

proteomics_tbl %>%
  rbind(metabolomics_tbl) %>%
  dplyr::rename(`Event Sequence` = event_sequence) %>%
  tidyr::pivot_wider(
    names_from = `Omics Type`,
    values_from = n,
    values_fill = 0
  ) %>%
  flextable::flextable() %>%
  atriReporter:::ft_add_abcds_theme() %>%
  flextable::width(width = 5.25 / 3)

```